// app/frontend/src/components/CodeEditor.vue
<template>
  <div class="code-editor-overlay" @click.self="$emit('close')">
    <div class="code-editor-modal">
      <!-- Header -->
      <div class="modal-header">
        <h2 class="modal-title">生成的代码</h2>
        <div class="header-actions">
          <button @click="downloadCode" class="action-btn">
            <svg class="btn-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor">
              <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4M7 10l5 5 5-5M12 15V3" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
            </svg>
            下载
          </button>
          <button @click="$emit('close')" class="action-btn">关闭</button>
        </div>
      </div>

      <!-- Tabs -->
      <div class="tabs-container">
        <div class="tabs-list">
          <button
            v-for="tab in tabs"
            :key="tab.value"
            @click="activeTab = tab.value"
            class="tab-button"
            :class="{ active: activeTab === tab.value }"
          >
            {{ tab.label }}
          </button>
        </div>
      </div>

      <!-- Code Content -->
      <div class="code-content">
        <button @click="copyCode(activeTab)" class="copy-button">
          <svg v-if="copiedTab !== activeTab" class="btn-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor">
            <rect x="9" y="9" width="13" height="13" rx="2" ry="2" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
            <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
          </svg>
          <svg v-else class="btn-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor">
            <polyline points="20 6 9 17 4 12" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
          </svg>
          {{ copiedTab === activeTab ? '已复制' : '复制' }}
        </button>
        <div class="code-scroll">
          <pre class="code-block"><code>{{ currentCode }}</code></pre>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue';
import type { GeneratedCode } from '../types';

interface Props {
  code: GeneratedCode;
}

const props = defineProps<Props>();
defineEmits<{
  (e: 'close'): void;
}>();

const tabs = [
  { label: 'HTML', value: 'html' },
  { label: 'CSS', value: 'css' },
  { label: 'JavaScript', value: 'javascript' }
];

const activeTab = ref<'html' | 'css' | 'javascript'>('html');
const copiedTab = ref<string | null>(null);

const currentCode = computed(() => {
  return props.code[activeTab.value] || '';
});

const copyCode = (tab: string) => {
  const code = props.code[tab as keyof GeneratedCode];
  navigator.clipboard.writeText(code);
  copiedTab.value = tab;
  setTimeout(() => {
    copiedTab.value = null;
  }, 2000);
};

const downloadCode = () => {
  const content = `
HTML文件:
${props.code.html}

---

CSS文件:
${props.code.css}

---

JavaScript文件:
${props.code.javascript}
  `;

  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = 'generated-code.txt';
  a.click();
  URL.revokeObjectURL(url);
};
</script>

<style scoped>
.code-editor-overlay {
  position: fixed;
  inset: 0;
  background: rgba(0, 0, 0, 0.8);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 50;
  padding: 1rem;
}

.code-editor-modal {
  background: #0A0A0A;
  border: 1px solid #2A2A2A;
  border-radius: 0.5rem;
  width: 100%;
  max-width: 56rem;
  height: 80vh;
  display: flex;
  flex-direction: column;
}

.modal-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 1rem;
  border-bottom: 1px solid #2A2A2A;
}

.modal-title {
  font-size: 1.25rem;
  font-weight: 700;
  color: white;
  margin: 0;
}

.header-actions {
  display: flex;
  gap: 0.5rem;
}

.action-btn {
  background: #1A1A1A;
  border: 1px solid #2A2A2A;
  color: #9CA3AF;
  padding: 0.5rem 1rem;
  border-radius: 0.375rem;
  cursor: pointer;
  display: flex;
  align-items: center;
  gap: 0.5rem;
  font-size: 0.875rem;
  transition: all 0.2s;
}

.action-btn:hover {
  background: #2A2A2A;
  color: white;
}

.btn-icon {
  width: 1rem;
  height: 1rem;
}

.tabs-container {
  background: #1A1A1A;
  border-bottom: 1px solid #2A2A2A;
}

.tabs-list {
  display: flex;
  padding: 0.5rem;
  gap: 0.25rem;
}

.tab-button {
  background: transparent;
  border: none;
  color: #9CA3AF;
  padding: 0.5rem 1rem;
  border-radius: 0.375rem;
  cursor: pointer;
  font-size: 0.875rem;
  transition: all 0.2s;
}

.tab-button:hover {
  background: #2A2A2A;
}

.tab-button.active {
  background: #6366F1;
  color: white;
}

.code-content {
  flex: 1;
  position: relative;
  overflow: hidden;
}

.copy-button {
  position: absolute;
  top: 1rem;
  right: 1rem;
  z-index: 10;
  background: #1A1A1A;
  border: 1px solid #2A2A2A;
  color: #9CA3AF;
  padding: 0.5rem 1rem;
  border-radius: 0.375rem;
  cursor: pointer;
  display: flex;
  align-items: center;
  gap: 0.5rem;
  font-size: 0.875rem;
  transition: all 0.2s;
}

.copy-button:hover {
  background: #2A2A2A;
  color: white;
}

.code-scroll {
  height: 100%;
  overflow: auto;
}

.code-block {
  padding: 1.5rem;
  font-size: 0.875rem;
  font-family: 'Fira Code', 'Courier New', monospace;
  color: #E5E7EB;
  background: #0A0A0A;
  margin: 0;
  white-space: pre-wrap;
  word-wrap: break-word;
}
</style>

// app/frontend/src/components/CodeEditor.tsx
import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Copy, Check, Download } from 'lucide-react';
import { GeneratedCode } from '@/types';

interface CodeEditorProps {
  code: GeneratedCode;
  onClose: () => void;
}

export default function CodeEditor({ code, onClose }: CodeEditorProps) {
  const [copiedTab, setCopiedTab] = useState<string | null>(null);

  const copyToClipboard = (text: string, tab: string) => {
    navigator.clipboard.writeText(text);
    setCopiedTab(tab);
    setTimeout(() => setCopiedTab(null), 2000);
  };

  const downloadCode = () => {
    const zip = `
HTML文件:
${code.html}

---

CSS文件:
${code.css}

---

JavaScript文件:
${code.javascript}
    `;

    const blob = new Blob([zip], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'generated-code.txt';
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 bg-black/80 flex items-center justify-center z-50 p-4">
      <div className="bg-[#0A0A0A] border border-[#2A2A2A] rounded-lg w-full max-w-4xl h-[80vh] flex flex-col">
        {/* Header */}
        <div className="flex items-center justify-between p-4 border-b border-[#2A2A2A]">
          <h2 className="text-xl font-bold text-white">生成的代码</h2>
          <div className="flex gap-2">
            <Button
              variant="outline"
              size="sm"
              onClick={downloadCode}
              className="bg-[#1A1A1A] border-[#2A2A2A] text-[#9CA3AF] hover:bg-[#2A2A2A] hover:text-white"
            >
              <Download className="w-4 h-4 mr-2" />
              下载
            </Button>
            <Button
              variant="outline"
              size="sm"
              onClick={onClose}
              className="bg-[#1A1A1A] border-[#2A2A2A] text-[#9CA3AF] hover:bg-[#2A2A2A] hover:text-white"
            >
              关闭
            </Button>
          </div>
        </div>

        {/* Code Tabs */}
        <Tabs defaultValue="html" className="flex-1 flex flex-col">
          <TabsList className="bg-[#1A1A1A] border-b border-[#2A2A2A] rounded-none p-2">
            <TabsTrigger 
              value="html"
              className="data-[state=active]:bg-[#6366F1] data-[state=active]:text-white"
            >
              HTML
            </TabsTrigger>
            <TabsTrigger 
              value="css"
              className="data-[state=active]:bg-[#6366F1] data-[state=active]:text-white"
            >
              CSS
            </TabsTrigger>
            <TabsTrigger 
              value="javascript"
              className="data-[state=active]:bg-[#6366F1] data-[state=active]:text-white"
            >
              JavaScript
            </TabsTrigger>
          </TabsList>

          <TabsContent value="html" className="flex-1 m-0 relative">
            <Button
              variant="outline"
              size="sm"
              onClick={() => copyToClipboard(code.html, 'html')}
              className="absolute top-4 right-4 z-10 bg-[#1A1A1A] border-[#2A2A2A] text-[#9CA3AF] hover:bg-[#2A2A2A] hover:text-white"
            >
              {copiedTab === 'html' ? (
                <>
                  <Check className="w-4 h-4 mr-2" />
                  已复制
                </>
              ) : (
                <>
                  <Copy className="w-4 h-4 mr-2" />
                  复制
                </>
              )}
            </Button>
            <ScrollArea className="h-full">
              <pre className="p-6 text-sm font-mono text-[#E5E7EB] bg-[#0A0A0A]">
                <code>{code.html}</code>
              </pre>
            </ScrollArea>
          </TabsContent>

          <TabsContent value="css" className="flex-1 m-0 relative">
            <Button
              variant="outline"
              size="sm"
              onClick={() => copyToClipboard(code.css, 'css')}
              className="absolute top-4 right-4 z-10 bg-[#1A1A1A] border-[#2A2A2A] text-[#9CA3AF] hover:bg-[#2A2A2A] hover:text-white"
            >
              {copiedTab === 'css' ? (
                <>
                  <Check className="w-4 h-4 mr-2" />
                  已复制
                </>
              ) : (
                <>
                  <Copy className="w-4 h-4 mr-2" />
                  复制
                </>
              )}
            </Button>
            <ScrollArea className="h-full">
              <pre className="p-6 text-sm font-mono text-[#E5E7EB] bg-[#0A0A0A]">
                <code>{code.css}</code>
              </pre>
            </ScrollArea>
          </TabsContent>

          <TabsContent value="javascript" className="flex-1 m-0 relative">
            <Button
              variant="outline"
              size="sm"
              onClick={() => copyToClipboard(code.javascript, 'javascript')}
              className="absolute top-4 right-4 z-10 bg-[#1A1A1A] border-[#2A2A2A] text-[#9CA3AF] hover:bg-[#2A2A2A] hover:text-white"
            >
              {copiedTab === 'javascript' ? (
                <>
                  <Check className="w-4 h-4 mr-2" />
                  已复制
                </>
              ) : (
                <>
                  <Copy className="w-4 h-4 mr-2" />
                  复制
                </>
              )}
            </Button>
            <ScrollArea className="h-full">
              <pre className="p-6 text-sm font-mono text-[#E5E7EB] bg-[#0A0A0A]">
                <code>{code.javascript}</code>
              </pre>
            </ScrollArea>
          </TabsContent>
        </Tabs>
      </div>
    </div>
  );
}
